<a href="https://colab.research.google.com/github/Manasavasireddi/Login_Form/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:

arr_squared = arr**2
print(arr_squared)


[ 1  4  9 16 25]


In [6]:

arr_added = arr + 5
print(arr_added)


[ 6  7  8  9 10]


In [7]:

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result_matrix = np.dot(matrix1, matrix2)
print(result_matrix)

[[19 22]
 [43 50]]


In [8]:

from scipy.integrate import quad
def f(x):
    return x**2
result, error = quad(f, 0, 1)

print("Result of integration:", result)
print("Estimated error:", error)

Result of integration: 0.33333333333333337
Estimated error: 3.700743415417189e-15
